### ISSUE TITLE
Ошибки после удаления задачи

### ISSUE THREAD

**Issue by radist** [centosadmin/redmine_recurring_tasks#3]
Если удалить задачу у который были заданы "повторы", при выполнении
 
```
$ RAILS_ENV=production bundle exec rake redmine_recurring_tasks:exec
```
Вот такой трейс

```
undefined method `author' for nil:NilClass
/home/redmine/web/rm.rubium.ru/public_html/plugins/redmine_recurring_tasks/lib/tasks/process.rake:14:in `block (3 levels) in <top (required)>'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `each'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `block in find_each'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:50:in `find_each'
/home/redmine/web/rm.rubium.ru/public_html/plugins/redmine_recurring_tasks/lib/tasks/process.rake:7:in `block (2 levels) in <top (required)>'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/redmine/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/redmine/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.3.3/bin/rake:22:in `load'
/home/redmine/.rvm/gems/ruby-2.3.3/bin/rake:22:in `<main>'
/home/redmine/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/home/redmine/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by olemskoi** [comment]
Исправлено. Для новых пользователей плагина будет всё теперь нормально, а для текущих пользователей нужно будет пересоздать базу плагина (внимание: текущие расписания удалятся!).

rake redmine:plugins:migrate NAME=redmine_recurring_tasks VERSION=0
rake redmine:plugins:migrate NAME=redmine_recurring_tasks
