### ISSUE TITLE
Problem with sameersbn/docker-redmine:4.0.3 docker image

### ISSUE THREAD

**Issue by robsonmantovani** [centosadmin/redmine_recurring_tasks#56]
I'm trying use recurring_tasks plugin with sameersbn/docker-redmine:4.0.3 docker image with no success. 

When i add a new recurring_task i got this error 500: 

```
POST "/recurring_tasks" for 138.118.128.2 at 2019-05-29 13:12:43 -0300
Processing by RecurringTasksController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"VdqHBEQkkFPmfO0kD/bt5ZUVlDWEDcdNp4bEKkIRdSgC3L9N43Kfa1/brEen/xYNWFUd1Oa/QSHhWgozeW4A3Q==", "issue_id"=>"46459", "recurring_task"=>{"tracker_id"=>"41", "time(1i)"=>"2000", "time(2i)"=>"1", "time(3i)"=>"1", "time(4i)"=>"02", "time(5i)"=>"00", "months"=>["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], "client_run_type"=>"week_days", "monday"=>"0", "tuesday"=>"0", "wednesday"=>"0", "thursday"=>"0", "friday"=>"0", "saturday"=>"0", "sunday"=>"0"}, "commit"=>"Adicionar"}
  Current user: robson.mantovani (id=24)
Completed 500 Internal Server Error in 20ms (ActiveRecord: 4.0ms)

ActiveRecord::MultiparameterAssignmentErrors (1 error(s) on assignment of multiparameter attributes [error on assignment [2000, 1, 1, 2, 0] to time (undefined method `utc' for {1=>2000, 2=>1, 3=>1, 4=>2, 5=>0}:Hash)]):

plugins/redmine_recurring_tasks/app/controllers/recurring_tasks_controller.rb:18:in `create'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by olemskoi** [comment]
Did you run migrations?
